{% set name = "scrypt" %}
{% set version = "0.8.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d226c1c6744fb2e308b391410669b1df5cfe82637ffcb5ed489bf82b2d2eb78

build:
  number: 0
  script:
    - set SCRYPT_WINDOWS_LINK_LEGACY_OPENSSL=0  # [win]
    - "{{ PYTHON }} %RECIPE_DIR%\\fix_openssl_win.py setup.py"     # [win]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - openssl
    - cffi >=1.7
  run:
    - python
    - openssl
    - cffi >=1.7

test:
  imports:
    - scrypt

about:
  home: https://github.com/holgern/py-scrypt
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/holgern/py-scrypt
  doc_url: https://github.com/holgern/py-scrypt
  summary: This is a set of Python bindings for the scrypt key derivation function.

extra:
  recipe-maintainers:
    - jan-janssen
    - holgern
