{% set name = "scrypt" %}
{% set version = "0.8.13" %}
{% set sha256 = "1377B1ADC98C4152694BF5D7E93B41A9D2E9060AF69B747CFAD8C93AC426F9EA" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 3
  script:
    - set SCRYPT_WINDOWS_LINK_LEGACY_OPENSSL=1  # [win and py==27]
    - set SCRYPT_WINDOWS_LINK_LEGACY_OPENSSL=0  # [win and py!=27]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - openssl
    - cffi >=1.7
  run:
    - python
    - openssl
    - cffi >=1.7

test:
  imports:
    - scrypt
  commands:
    - conda inspect linkages -p $PREFIX scrypt  # [not win]
    - conda inspect objects -p $PREFIX scrypt   # [osx]

about:
  home: https://bitbucket.org/mhallin/py-scrypt/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://bitbucket.org/mhallin/py-scrypt/
  doc_url: https://bitbucket.org/mhallin/py-scrypt/
  summary: 'This is a set of Python bindings for the scrypt key derivation function.'

extra:
  recipe-maintainers:
    - holgern
