{% set name = "scrypt" %}
{% set version = "0.8.7" %}
{% set sha256 = "b97744546656d98c4eff72da7856067ba21a538c34d519a346d4be3a66385342" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - openssl                      # [not win]
  run:
    - openssl                      # [not win]
    - python

test:
  imports:
    - scrypt
  commands:
    - conda inspect linkages -p $PREFIX scrypt  # [not win]
    - conda inspect objects -p $PREFIX scrypt   # [osx]

about:
  home: https://bitbucket.org/mhallin/py-scrypt/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://bitbucket.org/mhallin/py-scrypt/
  doc_url: https://bitbucket.org/mhallin/py-scrypt/
  summary: 'This is a set of Python bindings for the scrypt key derivation function.'

extra:
  recipe-maintainers:
    - holgern
